# Generated by Django 4.2.2 on 2023-06-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('tg', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Username')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион проживания')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Населенный пункт')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
    ]
